### ISSUE TITLE
investigate / fix failing travis tests

### ISSUE THREAD

**Issue by WMDE-Fisch** [wmde/Lizenzverweisgenerator#75]
Some of the test fail when run on the console - they succeed in the browser though. They are deactivated for Travis atm.

**Comment by wmde-manicki** [comment]
There are actually two things that result in tests failing on Travis (and also when run from command line on local machine). Both only concern tests calling API:
1. By default all tests have to finish in 5 seconds.
2. Apparently, PhantomJS does not handle protocol-relative urls which are used broadly in Attribution Generator. When doing an API call to `commons.wikimedia.org/w/api.php`, PhantomJS is trying to send an ajax request to `file://commons.wikimedia.org/w/api.php` and, obviously, hangs.

Issue 1 is not a real problem. We can (and will) raise the timeout of the test runner to some reasonable value allowing all API calls to finish and it should be enough.
Issue 2 is a bigger problem. It could be partially (for part of tests) fixed by simply providing protocol explicitly  in urls in tests. This would unfortunately only work for part of tests. In other cases some more work needs to be done.

I will continue looking into this. It would be also good to know if we actually want to use protocol-relative URLs in URLs in Commons and Wikipedias (aren't in all of these urls starting with `http://` being always translated to `https://`?)

**Comment by tobijat** [comment]
Moved to https://phabricator.wikimedia.org/T107023.
